site_name: PymordialBlue
site_description: The universal python automation framework.
site_url: https://github.com/IAmNo1Special/PymordialBlue
repo_url: https://github.com/IAmNo1Special/PymordialBlue
repo_name: IAmNo1Special/PymordialBlue

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - User Guide:
      - Overview: user_guide/index.md
      - Getting Started: user_guide/getting_started.md
      - App Management: user_guide/app_management.md
      - Configuration: user_guide/configuration.md
      - Core Concepts: user_guide/core_concepts.md
      - Extract Strategies: user_guide/extract_strategies.md
      - Devices:
          - ADB: user_guide/devices/adb.md
          - BlueStacks: user_guide/devices/bluestacks.md
          - UI: user_guide/devices/ui.md
          - Tesseract: user_guide/devices/tesseract.md
  - Reference:
      - Controller: reference/controller.md
      - App Model: reference/android_app.md
      - Devices: reference/devices.md
      - Utilities: reference/utils.md
